# 1. Numpy

In [2]:
import numpy as np


## 1.1 Array

- Các phần tử trong array của numpy phải cùng dữ liệu

In [3]:
a = np.array([1, 2, 3])
print(a)


[1 2 3]


- Nếu đen xen các phần tử khác kiểu dữ liệu trong array của numpy --> ép kiểu các phần tử thành cùng kiểu `string`

In [4]:
b = np.array([2.3, '2', 3])
print(b)


['2.3' '2' '3']


In [5]:
# 1. kiểm tra kiểu dữ liệu của array a
print('Kiểu dữ liệu của a:',type(a))

# 2. kiểm tra chiều của array a
print('Kích thước theo từng chiều của a:',a.shape)

# 3. truy xuất phần tử
print('a[1]:',a[1])

# 4. Thay đổi giá trị phần tử của a
print(a)
print('a[2] lúc đầu:',a[2])
a[2] = 5
print('a[2] lúc sau:',a[2])
print(a)


Kiểu dữ liệu của a: <class 'numpy.ndarray'>
Kích thước theo từng chiều của a: (3,)
a[1]: 2
[1 2 3]
a[2] lúc đầu: 3
a[2] lúc sau: 5
[1 2 5]


In [6]:
# Tạo ra ma trận a
a = np.array([[1, 2], [3, 4]])
print('Ma trận a:',a, sep='\n')


Ma trận a:
[[1 2]
 [3 4]]


In [7]:
print('Số chiều của ma trận a:', a.shape)
print('2 hàng và 2 cột của ma trận a')


Số chiều của ma trận a: (2, 2)
2 hàng và 2 cột của ma trận a


In [8]:
# Tạo ra 1 tensor --> nối 2 ma trận thành 3 chiều
a = np.array([[[1,2] , [3, 4]],
              [[5, 7], [7, 8]] ])
print('tensor a:', a, sep='\n')


tensor a:
[[[1 2]
  [3 4]]

 [[5 7]
  [7 8]]]


In [9]:
print('Số chiều của tensor a:', a.shape)
print('2 hàng, 2 cột, 2 chiều')


Số chiều của tensor a: (2, 2, 2)
2 hàng, 2 cột, 2 chiều


# 2. Khởi tạo mảng cho trước có các hàm ones(), zeros(), random.random()

- Muốn khởi tạo array nhiều chiều ==> khổi tạo bằng tuple

In [10]:
a = np.zeros((2, 2)) # tạo ra array 2 chiều toàn 0
print(a)


[[0. 0.]
 [0. 0.]]


In [11]:
b = np.ones((1, 2)) # tạo ra array 2 chiều toàn 1
print(b)


[[1. 1.]]


In [12]:
# tạo ma trận có kích thước (2, 2) toàn bằng 1 hàng số ==> dùng hàm full()
c = np.full((2, 2), 7)
print(c)


[[7 7]
 [7 7]]


In [13]:
# 1 cách tương tự như hàm full
c = np.ones((2, 2)) * 7
print(c)


[[7. 7.]
 [7. 7.]]


In [14]:
# Tạo ma trận đơn vị bằng hàm eye(kích thước n)
d = np.eye(4)
print(d)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# tạo ma trận ngẫu nhiên bằng hàm random.random ==> và sẽ khởi tạo ngẫu nhiên từ 0 -> 1
e = np.random.random((2, 2))
print(e)


[[0.48606336 0.98083192]
 [0.98852241 0.88151365]]


# 3. Tạo ra mảng với các giá trị theo quy luật

In [16]:
f = np.arange(10, 50, 5)
print(f)


[10 15 20 25 30 35 40 45]


## Hàm linspace() --> tạo ra các giá trị chia đều

In [17]:
g = np.linspace(0, 1, num=11)  # số đầu tiên: số bắt đầu, số thứ 2: số kết thúc, số thứ 3: số phần tử muốn lấy
print(g)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


## 4. Muốn tạo array bằng cách chồng (`stack`) các array cho trước theo chiều `ngang\dọc` thì ta sẽ dùng các phương thức sau:

- `vstack() or row_stack()` cho (vertical - chiều dọc)
- `hstack() or column_stack()` cho (horizotaln - chiều ngang)

- Tham số truyền vào hàm phải là `tuple`

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('Array a:',a)
print('Array b:',b)


Array a: [1 2 3]
Array b: [4 5 6]


In [19]:
vertical = np.vstack((a, b))
print('vertical:\n', vertical)
print(vertical.shape)


vertical:
 [[1 2 3]
 [4 5 6]]
(2, 3)


In [20]:
horizontal = np.hstack((a, b))
print('Horizontal:\n', horizontal)
print(horizontal.shape)


Horizontal:
 [1 2 3 4 5 6]
(6,)


- Viêc slice 1 biến trên ma trận --> tham chiếu đến ma trận con

==> dẫn đến việc khi thay đổi giá trị của biến tham chiếu ==> thay đổi giá trị ma trân đó luôn

In [21]:
a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12], 
              [13, 14, 15, 16] ])
print('Ma trận a gốc ban đầu:\n',a)
print(a.shape)


Ma trận a gốc ban đầu:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)


In [22]:
# giá trị b tham chiếu
b = a[:2, 1:3]
print('Giá trị tham chiếu của b sau khi slice:\n', b)


Giá trị tham chiếu của b sau khi slice:
 [[2 3]
 [6 7]]


In [23]:
# Nhưng b làm thay chiếu ==> thay đổi biến tham chiếu ==> thay đổi đến ptu được tham chiếu
print('a[0, 1] ban đầu:', a[0, 1])
print('b là:\n', b)
b[0,0] = 3
print('thay đổi biến tham chiếu b[0, 0]:', b[0,1])
print('a[0][1] ban đầu:', a[0,1])


a[0, 1] ban đầu: 2
b là:
 [[2 3]
 [6 7]]
thay đổi biến tham chiếu b[0, 0]: 3
a[0][1] ban đầu: 3


In [24]:
# a sau khi thay đổi
print('ma trận a sau khi thay đổi tham chiếu:\n', a)


ma trận a sau khi thay đổi tham chiếu:
 [[ 1  3  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# 5. Giảm chiều array khi tạo lát cắt

In [32]:
# Tạo ma trận a (3, 4)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


- Các cách thức lấy ra dòng sô 2

- Khi sử dụng chỉ mục là số nguyên ==> chiều của slice sẽ bị giảm
- Khi sử duụg chi muc là lát cắt ==> giữ nguyên chiều của slice so với dữ lieệ gốc

In [30]:
# solution 1: take row 1 and all columns
row_r1 = a[1, :]
print("row_r1:", row_r1, row_r1.shape)  # just one dimension


# solution 2 to take the second row:
row_r2 = a[1:2, :]
print("row_r2:", row_r2, row_r2.shape)  # just two demension

# solution 3 to take the second row
row_r3 = a[[1], :]
print("row_r3:", row_r3, row_r3.shape)


row_r1: [5 6 7 8] (4,)
row_r2: [[5 6 7 8]] (1, 4)
row_r3: [[5 6 7 8]] (1, 4)


In [34]:
# Khi thực hiện trên cột
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)


[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


# 6. Cơ chế đánh chỉ mục

- Chỉ mục là mảng số nguyen (`Integer array indexing`) ==> Tao ra array tư phân tư bat ky trong array gốc thay vì dùng slice

# Đây là điêm khac biet cua numpy so voi list

In [43]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print('a Gốc:')
print(a)
print()

# VD chỉ mục dạng số nguyên
# Kết quả trả về là array 1 chiều với 3 phần tử shape(3,)

print(a[[0, 1, 2],[0, 1, 0]]) # Ở đây sẽ tạo array với các phần tử tương ứng như vd dưới

# Tương tự
print(np.array([a[0,0], a[1, 1], a[2, 0]]))


a Gốc:
[[1 2]
 [3 4]
 [5 6]]

[1 4 5]
[1 4 5]


In [54]:
# Tạo array 2 chiều với kích thước (4, 3)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
# Tạo array chỉ mục
b = np.array([0, 2, 0, 1])

# Mỗi dòng lấy 1 phần tử, tại các cột có chỉ mục b
print(a[np.arange(4), b]) # [0 1 2 3],[0 2 0 1] ==> [a[0, 0], a[1, 2], a[2, 0], a[3, 1]]


[ 1  6  7 11]


In [58]:
# Cùng tăng 10 đơn vị cho từng phần tử của mỗi dòng, tại các cột có chỉ mục b
a[np.arange(4), b] += 10
print(a)


[[11  2  3]
 [ 4  5 20]
 [17  8  9]
 [10 23 12]]


## 7. Chỉ muc là mảng boolean

- chỉ muụ daạg boolean --> loc ra ptu thoa tinh chat nao do

In [67]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5,6]])

bool_idx = (a > 2)
print(a)

# mảng này trả về kích thước giống mảng a nhưng giá trị trả về là kiểm tra điều kiện
print(bool_idx, bool_idx.shape)
bool_idx


[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]] (3, 2)


array([[False, False],
       [ True,  True],
       [ True,  True]])

In [66]:
# Lấy ra các giá trị > 2

print(a[bool_idx])
"""
    Khi gọi a[bool_idx] ==> np trích xuất các phần tử tại vị trí có giá trị là True ==> trả về array 1 chiều    
    - Có nghĩa là mảng a sẽ duyệt tuần tự qua có chỉ số là true mới in ra
"""

# viết gọn lại tương tự
print(a[a > 2])


[3 4 5 6]
[3 4 5 6]


# 8. Các haà laá ra chỉ muc

- `argmax`: chi so max
- `argmin`: chi so min
- `argsort`: chi so cac phan tu da sap xep tang dan
- `where`: chi so cac phan tu thoa dieu kien nao do

In [80]:
a = np.array([1, 2, 0, -9, 4, 6, 9])

# chỉ số max
print('Chi so max',np.argmax(a))

# chỉ số min
print('Chi so min',np.argmin(a))



Chi so max 6
Chi so min 3


In [82]:
# lay ra cac phan tu sap xep tang dan
print('chi so cac phan tu sap xep tang dan', np.argsort(a))
print('Mang sap xep tang dan the chi so:')
for idx in np.argsort(a):
    print(a[idx], end= ' ')
print()
# Lấy chỉ số cac phan tu sau kii sap xep giam dan theo gia tri
# [::-1]: cac lay chi muc lat cach theo thu tu nghich dao
print('Chi so theo thu tu nghich dao giam dan:',np.argsort(a)[::-1])


chi so cac phan tu sap xep tang dan [3 2 0 1 4 5 6]
Mang sap xep tang dan the chi so:
-9 0 1 2 4 6 9 
Chi so theo thu tu nghich dao giam dan: [6 5 4 1 0 2 3]


In [84]:
# Lấy ra chỉ mục thỏa tính chất
# Trả về tuple --> danh sach chỉ mục là phần tử đầu tiên
# sử dụng [0] để lấy danh sách chỉ mục
print(np.where(a > 5)[0])

# Lấy chỉ mục các phần tử thỏa tính chất
# Lấy chỉ mục tất cả phần tử lớn nhất trong mảng
print(np.where(a >= a[np.argmax(a)])[0])


[5 6]
[6]


# 9. KDL array

In [88]:
# Để numpy tự chọn kiểu dữ liệu
x = np.array([1, 2])
y = np.array([1, 2.0, ])
z = np.array([1, 2], dtype=np.int64) # chỉ định kiểu dữ liệu

print(x.dtype, y.dtype, z.dtype)


int64 float64 int64


# 10. Hàm tính toán

- Sử dung `%%time` để đo thơi gian thuc thi

In [96]:
a = np.random.random(100000000)


In [97]:
%%time
x = np.sum(a)


CPU times: total: 125 ms
Wall time: 137 ms


In [98]:
%%time
x = 0
for element in a:
    x += element



CPU times: total: 12.5 s
Wall time: 13.1 s


## Co gang su dung vector hoa bang ham `np.add()`

In [99]:
x = np.array([[1,2], [3, 4]], dtype=np.float64)
y = np.array([[5,6], [7, 8]], dtype=np.float64)



# Tổng theo từng phần tử, thực hiện bằng 2 cách

In [ ]:
%%time
print(x + y)


[[ 6.  8.]
 [10. 12.]]
CPU times: total: 15.6 ms
Wall time: 2 ms


In [ ]:
%%time
print(np.add(x, y))


[[ 6.  8.]
 [10. 12.]]
CPU times: total: 0 ns
Wall time: 0 ns


# phép trừ

In [ ]:
print(x - y)
print(np.subtract(x, y))


[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


# Phép nhân

In [104]:
# Phép nhân: tích theo từng phần tử (`element wise product`)
print(x * y)
print(np.multiply(x, y))


[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


# Phép chia

In [105]:
print(x / y)
print(np.divide(x, y))


[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


# Laá can theo tung phan tu

In [106]:
print(np.sqrt(x))


[[1.         1.41421356]
 [1.73205081 2.        ]]


- `*`: tích theo từng phần tử, `không phải nhân ma trận`

==> dùng hàm `dot()`: để tính tích  `các vector`, `vector - ma trận`, `ma trận - ma trận`
==> `dot()`: vừa hàm của numpy, vừa phương thức array

In [7]:
x = np.array([[1,2], [3, 4]])
y = np.array([[5,6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print(x, x.shape)
print(y, y.shape)
print(v, v.shape)
print(w, w.shape)

# inner product of vector; both are the same result
print(v.dot(w))
print(np.dot(v,w))


[[1 2]
 [3 4]] (2, 2)
[[5 6]
 [7 8]] (2, 2)
[ 9 10] (2,)
[11 12] (2,)
219
219


- Ta có thê dùng `@` thay cho toán tư dot

In [ ]:
print(v @ w)


219


In [6]:
# Cách nhân ma trận - vector
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)


[29 67]
[29 67]
[29 67]


In [8]:
# Cách nhân ma trận - ma trận
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


- các hàm min, max, sum

In [10]:
x = np.array([[1, 2], [3,4], [5,6]])
print(np.max(x))
print(np.min(x))
print(np.sum(x))
print(np.average(x))


6
1
21
3.5


- tính toán theo từng cọộ || từng hàng theo `axis`

In [ ]:
x = np.array([[1, 2], [3,4], [5,6]])
print('x gốc: ',x, sep='\n')
print()
# tìm max trên từng hàng ==> truyền vào axis
print(np.max(x, axis=0)) # tính max trên mỗi cột
print(np.max(x, axis=1)) # tính max trên mỗi hàng


x gốc: 
[[1 2]
 [3 4]
 [5 6]]

[5 6]
[2 4 6]


- chuyển đổi ma tran bằng `.T`

In [15]:
x = np.array([[1, 2], 
              [3,4], 
              [5,6]])
print('Ma trận x gốc:')
print(x, x.shape)

# chuyển đổi ma trận
print('Ma trận x sau khi chuyển vị:')
print(x.T, x.T.shape)


Ma trận x gốc:
[[1 2]
 [3 4]
 [5 6]] (3, 2)
Ma trận x sau khi chuyển vị:
[[1 3 5]
 [2 4 6]] (2, 3)


- Cách đổi chiều của ma trận bằng hàm `reshape`

In [21]:
x = np.array([1, 2, 3, 4, 5, 6])
print('X gốc ban đầu:')
print(x, x.shape)

# reshape thành (2, 3)
two_array = x.reshape(2, 3)
print('x reshape to (2, 3):')
print(two_array, two_array.shape)

# reshape thành (3, 2)
two_array_3 = x.reshape(3, 2)
print('x reshape to (3, 2):')
print(two_array_3, two_array_3.shape)


X gốc ban đầu:
[1 2 3 4 5 6] (6,)
x reshape to (2, 3):
[[1 2 3]
 [4 5 6]] (2, 3)
x reshape to (3, 2):
[[1 2]
 [3 4]
 [5 6]] (3, 2)


- VD 2:

In [30]:
x = np.array([[1], [2], [3]])
print(x)
x.shape


[[1]
 [2]
 [3]]


(3, 1)

In [31]:
# loại bỏ các tham số ko cần thiết để đưa về array 1 chiều với -1 
# ==> từ động điều chỉnh kích thước từ ma trận sang array
y = x.reshape(-1,)
print(y)
y.shape


[1 2 3]


(3,)

- TƯơng tự như hàm `squeeze()`

In [ ]:
z = x.squeeze()
print(z)
z.shape


[1 2 3]


(3,)

- Để chuyển tư 1D ==> 2D thì thêm 1 vào ví trị tham số còn lại truyền vào `tuple`

In [36]:
y.reshape((-1, 1))



array([[1],
       [2],
       [3]])

# Cơ chế `broadcasting`

- khi 1 array vói 1 scale ==> scale tự mở rông chiều tương ưng với array
- broadcasting có `2 quy tắc`:
    1. Nếu 2 array khác số chiều ==> kích thúướ chiều `ít hơn` sẽ đuợc `chèn phía đầu bên trái`
    2. Nếu shape 2 array `không khớp` ở chiều nào ==> array có `kích thước = 1` thì sẽ `kéo dài ở chiều đó`
    3. không chiều nào bằng nhau & ko có chiều = 1 ==> `lỗi ValueError`

In [ ]:
# VD cho quy tắc 1
a = np.array([1, 2, 3]) # array 1 chiều: shape(3,) ==> sẽ nhằm mở rộng thêm 1 chiều bên trái: shape(1, 3)
b = np.array([[4], [5], [6]]) # array 2 chiều: shape(3, 1)

print(a, a.shape)
print()
print(b, b.shape)

# broadcasting
print()
c = a + b # thêm quy tắc 2 nữa
print(c)
c.shape



[1 2 3] (3,)

[[4]
 [5]
 [6]] (3, 1)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


(3, 3)

In [ ]:
# vd quy tắc 2 lỗi nếu ko có chiều nào = 1 và không có chiều nào bằng nahu
a = np.array([[1], [2], [3], [4]]) # shape(4, 1)
b = np.array([[5, 6], [7, 8], [9, 10]]) # shape(3, 2)

# khi broadcasting khi khác chiều ==> bị ValueError: operands could not be broadcast
try:
    c = a + b
    print(c)
except ValueError:
    print('lỗi broadcast vì khác số chiều vi phạm quy tắc 2')



[[ 6  7]
 [ 9 10]
 [12 13]]


In [ ]:
# vd quy tắc 2
a = np.array([[1], [2], [3]]) # shape(3, 1): # array có shape(1) ==> kéo dài ở chiều đó bằng chiều còn lại của array
b = np.array([[5, 6], [7, 8], [9, 10]]) # shape(3, 2)

print(f'a.shape{a.shape}')
print(f'b.shape{b.shape}')

# broadcasting theo quy tắc 2
c = a + b # ==> a sẽ thành (3, 2)
print('c = a + b:',c, sep='\n')
print(f'c.shape{c.shape}')


a.shape(3, 1)
b.shape(3, 2)
c = a + b:
[[ 6  7]
 [ 9 10]
 [12 13]]
c.shape(3, 2)


In [ ]:
np.ones(shape=(2, 3), dtype='int')



array([[1, 1, 1],
       [1, 1, 1]])

In [4]:
np.array([1, 2, 3]) + [1, 2, 3]


array([2, 4, 6])

In [8]:
a = np.array([1, 2, 3]) + np.array([[1, 3, 4]])
print(np.array([1, 2, 3]).shape)
print(np.array([[1, 3, 4]]).shape)
print(a)
print(a.shape)


(3,)
(1, 3)
[[2 5 7]]
(1, 3)
